### ISSUE TITLE
DynamoDB TableName 

### ISSUE THREAD

**Issue by SwePalm** [aws-samples/aws-deeplens-coffee-leaderboard#2]
To be consistent with blog article:
"create a table. Use **Faces** as the table name"

 you need to change TableName from 'faces' to 'Faces' at line 66, 77, 132 in face_function.py

Same change at line 19 in application.py
..and leave a note to others that insert bucket name and check regions in this file as well ;-)

**Comment by JCoelhoo** [comment]
Files have been changed. Thanks!!
